# Common configuration.
AllCops:
  Exclude:
    - 'samples/**/*'

Metrics/MethodLength:
  CountComments: false
  Max: 10

Style/Documentation:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space